ARG KOSLI_CLI_VERSION=v0.1.33

# Build Base
FROM ghcr.io/kosli-dev/cli:$KOSLI_CLI_VERSION

RUN wget https://downloads-openshift-console.apps.kosli-demo.ji1t.p1.openshiftapps.com/amd64/linux/oc.tar -O /usr/bin/oc &&\
    chmod +x /usr/bin/oc

RUN wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
    chmod +x /usr/bin/yq
