name: Kosli Dev Demos - Kosli CLI - Container Workflow

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
    paths:
      - 'kosli-cli/**'

env:
  CONTAINER_REGISTRY_SERVER: ghcr.io
  CONTAINER_REGISTRY: ghcr.io/${{github.repository}}/kosli-cli
  IMAGE_CONTEXT: ./kosli-cli
  IMAGE_FILE: Containerfile
  IMAGE_NAME: kosli-cli
  IMAGE_DESCRIPTION: "Contains the Kosli CLI and other tools for usage in CI pipelines."
  IMAGE_SOURCE: ${{github.server_url}}/${{github.repository}}/kosli-cli

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
          
  kosli-cli:
    needs:
    - cancel-previous
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 
 
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry ${{ env.CONTAINER_REGISTRY_SERVER }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.CONTAINER_REGISTRY_SERVER }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.CONTAINER_REGISTRY }}
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix=sha-,format=long

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ${{ env.IMAGE_CONTEXT }}
          file: ${{ env.IMAGE_CONTEXT }}/${{ env.IMAGE_FILE }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.title=${{env.IMAGE_NAME}}
            org.opencontainers.image.description=${{env.IMAGE_DESCRIPTION}}
            org.opencontainers.image.url=${{env.CONTAINER_REGISTRY}}
            org.opencontainers.image.source=${{env.IMAGE_SOURCE}}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }} 
            org.opencontainers.image.created=${{ steps.prep.outputs.created }} 
            org.opencontainers.image.revision=${{ github.sha }}